### ISSUE TITLE
srsUE Support for 3700-3800 MHz, n78, TDD

### ISSUE THREAD

**Issue by SusmitaSumaiya** [srsran/srsRAN_4G#1124]
Hello,
I am trying to run a private network using USRP B210. I have tried to configure srsUE for our licensed band 3700-3800 MHz, n78, TDD using the value dl_earfcn = 653332. But it shows invalid earfcn  when I run the UE. I addition, The documentation says it only supports FDD bands. Is it possible to run UE with our licensed band? If possible, please suggest a compatible configuration for UE. 

I am having the following output while running the UE - 
Active RF plugins: libsrsran_rf_uhd.so libsrsran_rf_zmq.so
Inactive RF plugins:
Couldn't open , trying /home/usrp1/.config/srsran/ue.conf
Reading configuration file /home/usrp1/.config/srsran/ue.conf...

Built in Release mode using commit 5a4eb5d6c on branch master.

/home/usrp1/srsRAN_4G/lib/src/phy/common/phy_common.c:664: Invalid DL_EARFCN=653332
Opening 1 channels in RF device=default with args=USRP B210: num_recv_frames=64,num_send_frames=64
Supported RF device list: UHD zmq file
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 7.5.0; Boost_106501; UHD_4.4.0.0-68-g02558b69
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: USRP B210: num_recv_frames=64,num_send_frames=64,type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 2.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test...
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test...
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz...
[INFO] [B200] Actually got clock rate 23.040000 MHz.
RF device 'UHD' successfully opened
Waiting PHY to initialize ... done!
Attaching UE...
RF status: O=23, U=0, L=0
RF status: O=19, U=0, L=0
RF status: O=19, U=0, L=0

**Comment by ismagom** [comment]
Hi @SusmitaSumaiya , 

srsUE does not support TDD. Also, you are using the B210 with USB2, you need to connect it to a USB3 port
