### ISSUE TITLE
Unable to do cell search

### ISSUE THREAD

**Issue by Azukaa** [srsran/srsRAN_4G#1127]
Hi, I am new to SRSRan, anytime i perform a cell search, by using the "sudo srsue" command, I never get any cell to show up. I am suspecting an error from this out put. Can someone help  me out?

Below is the output i keep getting.

Active RF plugins: libsrsran_rf_uhd.so libsrsran_rf_zmq.so
Inactive RF plugins: 
Couldn't open , trying /home/azuka/.config/srsran/ue.conf
Reading configuration file /home/azuka/.config/srsran/ue.conf...
WARNING: Could not verify cpu0 scaling governor
WARNING: Could not verify cpu1 scaling governor

Built in Release mode using commit 5a4eb5d6c on branch master.

Opening 1 channels in RF device=default with args=default
Supported RF device list: UHD zmq file
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 7.5.0; Boost_106501; UHD_4.4.0.0-68-g02558b69
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
RF device 'UHD' successfully opened
Waiting PHY to initialize ... done!
Attaching UE...
......................
..............................................................
........
..............................................................................................................................................
..................................................................................................................^CStopping ..
^X---  exiting  ---

**Comment by xavierarteaga** [comment]
Hi Azukaa,
sorry for the delay.

I understand you expected the `srsue` to find a cell and connect to the cell as it was an out-of-the-shelf modem. I am afraid `srsue` operates differently, you need to specify the frequency and bandwidth of the cell you are connecting.

The [getting started guide](https://docs.srsran.com/projects/4g/en/latest/getting_started.html) will help you to set up an end-to-end network and to experiment with different configurations and log files. 

I am closing this issue for the time being. Reopen it if you need further advice.
