### ISSUE TITLE
I have installed srsran4g in ubuntu 18.04 , srsenb and srsepc were configured successfully. we read the contents (KI,OPC, OP) of the simcards by simcard reader and inserted them in user_db.csv file. the local simcards in our mobiles were able to discover the network created by SRSRAN. But when we try to connect to the network. It does not authenticate the credential from user_db.csv file,  what can be the issue here? Please guide , i am stuck here.

### ISSUE THREAD

**Issue by tajwersyed** [srsran/srsRAN_4G#1136]
## Issue Description ##
[Describe the issue in detail]

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by ismagom** [comment]
Please create a new issue. Don't use the title to explaim the problem. Follow the template amd attach log files.

Thanks for your feedback
