### ISSUE TITLE
Error timed out while receiving samples from UHD

### ISSUE THREAD

**Issue by jqhu27** [srsran/srsRAN_4G#1138]
## Issue Description ##
When I run srsENB, after running for a while it shows errors below
![Screenshot from 2023-03-31 11-48-35](https://user-images.githubusercontent.com/54186610/229169215-87925e15-382a-4479-a828-43c15c876f2a.png)

## Setup Details ##
Operation System: Ubuntu 20.04
Hardware: Dell Latitude3420
RF front-end: x310
UHD versions: UHD_4.1.0.6-120-g7e1ff96a

**Comment by yusky2003** [comment]
我也遇到了这个问题，但我用的是B210，请问你已经解决这个问题了吗？

**Comment by ismagom** [comment]
It seems there are problems using the USRP. have you tried running the UHD benchmarks and follow the UHD user guide?
