### ISSUE TITLE
SrsGUi Question

### ISSUE THREAD

**Issue by psi7** [srsran/srsRAN_4G#1139]
I am trying to trun srsGui after building and setting up srsGui and srsRan.
When it try to run srsenb and I want to have the gui plots I am getting:

> Trying to start a plot but plots are disabled ( ENABLE_GUI constant in sf_worker.cc)

 What should I do exaclty? I have been trying to fix it for a week.

**Comment by CatiaS11** [comment]
Hello ! 
You should go to root/.conf/srsend -> then when you edit the file you'll see a section called [GUI] and you have to enable GUI option there. I worked for me in any case. Check if you built srsGUI and srsRAN properly.

**Comment by CatiaS11** [comment]
srsenb*

**Comment by psi7** [comment]
i am running the command : srsenb --gui.enable=yes and it works now but I am getting the four basic diagrams (Channel Response Magnitude, PUSCH-Equalized Symbols, Channel Response Argument, PUCCH- Equalized Symbols) with the above command. Am I missing something? Are there other commands or diagrams that SRS can give me?

**Comment by CatiaS11** [comment]
> Thanks for the immediate response. I am running the command : srsenb --gui.enable=yes and it works now but I am getting the four basic diagrams (Channel Response Magnitude, PUSCH-Equalized Symbols, Channel Response Argument, PUCCH- Equalized Symbols) with the above command. Am I missing something? Are there other commands or diagrams that srsGUI can give me?

You can have only four diagrams I guess.

**Comment by xavierarteaga** [comment]
Hi @psi7,
@CatiaS11 is correct. Currently, only graphs are implemented.

You could potentially implement your plots by looking at the current examples.

I am closing this issue. Feel free to reopen if you have more questions.

**Comment by xavierarteaga** [comment]
Hi @psi7,
@CatiaS11 is correct. Currently, only these four graphs are implemented.

You could potentially implement your plots by looking at the current examples.

I am closing this issue. Feel free to reopen if you have more questions.
