### ISSUE TITLE
Use srsRAN to collect CSI reports of mobile phones on your computer

### ISSUE THREAD

**Issue by Violet-J** [srsran/srsRAN_4G#1149]
## Issue Description ##
Use srsRAN to collect CSI reports of mobile phones on your computer
## Setup Details ##

device:
Ubuntu18.04
usrpb210
phone
## Expected Behavior ##
[What you expect to happen]
Use srsRAN to collect CSI reports of mobile phones on your computer
## Steps to reproduce the problem ##

I want to collect the CSI report of the phone on the computer, but I changed the code without change, modified csi.c under lib/src/phy/phch, no change after recompiling, why is this, and I want to only run enb and not ue, I don't quite understand how I should do it.

**Comment by andrepuschmann** [comment]
I am afraid we can't help here without any further information on the changes. However, the purpose of the issues tracking here is not to discuss private changes to the repo but rather "real" issues with the official srsRAN code. I hope that makes sense.
