### ISSUE TITLE
srsUE in Raspberry Pi4B with USRP B210

### ISSUE THREAD

**Issue by soupurtion** [srsran/srsRAN_4G#1150]
## Issue Description ##
I am trying to run srsUE in Raspberry Pi 4B with USRP attached to it. But srsUE is hanged at "waiting for PHY to initiate". I know from a post back in Feb 2022 that srsRAN UE does not support in Raspberry Pi. **Is that still holds?**
Is there any way that I can still run with some configuration changes?

## Setup Details ##
I am using Raspberry Pi4B (4GB) with Ettus USRP B210. However, I tried even with ZMQ but results are the same.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/35415429/233709252-66056fe5-d89d-49ee-9829-1cb1e25b578a.png)

## Expected Behavior ##
Run srsUE.

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
Running the UE on the Pi4 is still not possible. The initial cell sync is just not optimized for it.
