### ISSUE TITLE
[5G SA] Can't connect UE to ENB and Core with two USRP b210

### ISSUE THREAD

**Issue by raulbarbosa1996** [srsran/srsRAN_4G#1151]
Hello.

Im trying to connect two usrp b210(One enb and the other UE).
The enb is registed on Core but the UE does not attach to enb and Core.
Please find the .conf files and the logs images attached.
I followed the this tutorial: https://docs.srsran.com/projects/4g/en/latest/app_notes/source/5g_sa_COTS/source/index.html#reference-clock.

Can someone help please?

[enb_standard.conf.txt](https://github.com/srsran/srsRAN_4G/files/11311933/enb_standard.conf.txt)
[rr.conf.txt](https://github.com/srsran/srsRAN_4G/files/11311936/rr.conf.txt)
[ue_standard.conf.txt](https://github.com/srsran/srsRAN_4G/files/11311937/ue_standard.conf.txt)

![image](https://user-images.githubusercontent.com/36931804/234042890-0e2e02e3-06dc-44f5-8b2e-351be491ecd8.png)
![image](https://user-images.githubusercontent.com/36931804/234043130-a1eac919-46b9-4c27-b162-1acb5a8079af.png)

**Comment by yzucyh** [comment]
Hi @raulbarbosa1996 ,
Can you share how you fixed this problem? It will be thankful.
