### ISSUE TITLE
srsEPC with zeroMQ failing

### ISSUE THREAD

**Issue by lkorley** [srsran/srsRAN_4G#1157]
## Issue Description ##
Attempting to run srsEPC with zeroMQ fails to initialize SGi and GTP-U
It is run as root and I have tried to directly set `cap_net_admin+eip` permissions for the srsepc binary, but no joy has been found.

## Setup Details ##
Running in `debian:bullseye-slim` docker container with flags  `--cap-add CAP_SYS_ADMIN --cap-add NET_ADMIN --security-opt apparmor=unconfined` 
compiled srsRAN_4G tagged version `release_22_10`

## Expected Behavior ##
Run srsEPC without error and create TUN device in default network namespace

## Actual Behaviour ##
```
Built in Release mode using commit 254cc719a on branch HEAD.


---  Software Radio Systems EPC  ---

Couldn't open , trying /root/.config/srsran/epc.conf
Reading configuration file /root/.config/srsran/epc.conf...
Couldn't open user_db.csv, trying /root/.config/srsran/user_db.csv
HSS Initialized.
MME S11 Initialized
MME GTP-C Initialized
MME Initialized. MCC: 0xf001, MNC: 0xff01
Could not initialize the SGi interface.
Could not initialize the SPGW's GTP-U.
Error initializing SP-GW
```

## Steps to reproduce the problem ##
[[Install and run with zeromq]](https://docs.srsran.com/projects/4g/en/latest/app_notes/source/zeromq/source/index.html#running-the-epc)

## Additional Information ##
Found this issue: https://github.com/srsran/srsRAN_4G/issues/992
But it did not yield a solution

**Comment by ismagom** [comment]
Issue fixed in #992
