### ISSUE TITLE
4G - srsENB cannot connect to srsUE

### ISSUE THREAD

**Issue by nkabigti** [srsran/srsRAN_4G#1159]
## Issue Description ## 
Hello,
I have been trying to connect srsENB and srsUE between two computers using two USRP X310s. According to the UHD test waveform, signals are present. However, the srsENB messages say that there is a failure to connect. I have tried multiple versions of 4G srsRAN, but the same messages from UE persist. The files below are from using version 23.04 of 4G srsRAN.

## Setup Details ##
Two separate Ubuntu PCs running on Ubuntu 20.04. Both PCs are not connected to any network aside from their connection with their respective USRP X310. The 1 GB port is being used for both X310s.
## Expected Behavior ##
The UE connects to the base station and I am given an IP address for the UE. I should be able to ping the computers from both sides.

## Actual Behaviour ##
UE and ENB start with no critical errors or warnings, yet the ENB fails to connect, UE messages say "Cell Selection" has completed with failure.

## Steps to reproduce the problem ##
Used in build directories
ENB PC:
sudo srsenb/src/srsenb
UE PC:
sudo srsue/src/srsue

## Additional Information ##
enb messages: 
[srsgnb_log.txt](https://github.com/srsran/srsRAN_4G/files/11384280/srsgnb_log.txt)
ue messages:
[srsue_log.txt](https://github.com/srsran/srsRAN_4G/files/11384285/srsue_log.txt)

config files:
[sibconf.txt](https://github.com/srsran/srsRAN_4G/files/11384310/sibconf.txt)
[ueconf.txt](https://github.com/srsran/srsRAN_4G/files/11384311/ueconf.txt)
[enbconf.txt](https://github.com/srsran/srsRAN_4G/files/11384312/enbconf.txt)
[rbconf.txt](https://github.com/srsran/srsRAN_4G/files/11384314/rbconf.txt)
[rrconf.txt](https://github.com/srsran/srsRAN_4G/files/11384315/rrconf.txt)

**Comment by andrepuschmann** [comment]
Hey - you need to carefully read the screen output. The eNB console clearly says:
`Failed to initiate S1 connection. Attempting reconnection in 10 seconds`

Since you don't even mention a core network in your explanation I guess you're not running one. I suggest to follow our app-notes https://docs.srsran.com/projects/4g/ 

Hope that helps.
