### ISSUE TITLE
5g sa connection between srsUE and Amari Callbox

### ISSUE THREAD

**Issue by rubidam** [srsran/srsRAN_4G#1165]
## Issue Description ##
I followed below manual to make a 5g sa connection between srsUE and Amari callbox.
https://docs.srsran.com/projects/4g/en/latest/app_notes/source/5g_sa_amari/source/index.html
However, srsUE cannot find cell and it just print 'RF status: O=5, U = 0, L = 0'

I tried to make lte connection with same devices but different configs, and it was connected easily. 
I also tried to use USRP X300 on srsUE, it showed similar results.

## Setup Details ##
PC with srsUE
OS : ubuntu 20.04
```
$ uhd_find_devices 
[INFO] [UHD] linux; GNU C++ version 9.2.1 20200304; Boost_107100; UHD_3.15.0.0-2build5
--------------------------------------------------
-- UHD Device 0
--------------------------------------------------
Device Address:
    serial: XXXXXX
    name: MyB200
    product: B200
    type: b200
```

## Expected Behavior ##
Find cell and attach with ue

### srsUE result with B200 usrp
![Screenshot from 2023-05-11 12-31-13](https://github.com/srsran/srsRAN_4G/assets/44969740/280c1767-f9f3-4f31-a8cb-38310882c2f4)

### srsUE result with X300 usrp
![Screenshot from 2023-05-12 15-01-22](https://github.com/srsran/srsRAN_4G/assets/44969740/3405ff2e-d467-4326-bd5f-dfae0b9619c1)

## Steps to reproduce the problem ##
I want to connect on n3 band between srsUE and Amari Callbox. Below files are ue and gnb configurations. 

[ue5.conf.txt](https://github.com/srsran/srsRAN_4G/files/11427367/ue5.conf.txt)
[gnb-sa-n3-short.cfg.txt](https://github.com/srsran/srsRAN_4G/files/11447868/gnb-sa-n3-short.cfg.txt)

## Additional Information ##
log_level is 'info'

### srsUE log with B200 usrp
[ue-info.log](https://github.com/srsran/srsRAN_4G/files/11447879/ue-info.log)
In line 48, I think SFN synchronization is a reason of this problem.
### srsUE log with X300 usrp
[ue_x.log.txt](https://github.com/srsran/srsRAN_4G/files/11459844/ue_x.log.txt)
In line 41, SFN synchronization is successful.
However, during SIB1 acquisition, SFN is not matched. (line 104)

**Comment by andrepuschmann** [comment]
Your RF settings aren't ideal. Low SNR, hight CFO. See
`2023-05-12T05:52:34.533404 [RRC-NR ] [I] Proc "Cell Selection" - Cell search found ARFCN=0 PCI=500 epre=-18.1 snr=-2.5 cfo=-4110.7 delay=-0.2  sfn=108 ssb_idx=0`

Try to adjust gains first. I see you have a GPSDO, so try to use it. But you might also need to use an external sync for the Amari callbox.
