### ISSUE TITLE
required NSA documents by using usrpB210

### ISSUE THREAD

**Issue by Sivanesh1992** [srsran/srsRAN_4G#1166]
Dear All,

Any one tested 5G NSA by using usrp B210. 
I am using below link to test NSA by using one UsrpB210

https://docs.srsran.com/projects/4g/en/latest/app_notes/source/5g_nsa_cots/source/index.html

but LTE only attaching ,not able to see the 5G network in NSA mode.

I want to know we need two usrpB210 to test NSA 5G ?

If Yes please guide me how to Deploy 5G NSA by using two usrpB210.

Regards,
Sivaneshkumar

**Comment by kazim425** [comment]
I am also facing the same issue, but I am using USRP x300/x310. 4G works perfectly, but it is not stable in 5G NSA mode.
