### ISSUE TITLE
srsUE could not synchronize SFN during cell selection

### ISSUE THREAD

**Issue by rubidam** [srsran/srsRAN_4G#1172]
## Issue Description ##
I want to make 5g sa connection between srsUE and Amari callbox. I asked similar issue before(#1165 ), but something is different.
In the previous issue, overflow always appeared in srsUE, so I thought that the overflow is the reason of synch failed. However, there is no overflow in this trials, but it still shows synchronization failed in cell selection. Does anyone know the reason?

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions
srsue - ubuntu 20.04, USRP B200, uhd_3.15.0

## Expected Behavior ##
successful cell selection and attach with ue

## Actual Behaviour ##
synch failed during cell selection

## Steps to reproduce the problem ##
[ue5.conf.txt](https://github.com/srsran/srsRAN_4G/files/11539551/ue5.conf.txt)

[ue_info.log](https://github.com/srsran/srsRAN_4G/files/11539468/ue_info.log)

**Comment by andrepuschmann** [comment]
It's likely the same as #1165 . Follow the suggestions there. Closing this
