### ISSUE TITLE
How to decode npdsch.pcap?

### ISSUE THREAD

**Issue by VLiu7** [srsran/srsRAN_4G#1173]
## Issue Description ##
Hi!
I followed this tutorial (https://docs.srsran.com/projects/4g/en/latest/app_notes/source/nbiot/source/index.html) to set up a NB-IoT testbed. 
But I cannot decode `npdsch.pcap` with wireshark.
I found this pcap is with `DLT` 147, but this tutorial(https://docs.srsran.com/projects/4g/en/latest/usermanuals/source/srsue/source/2_ue_getstarted.html?highlight=pcap#observing-results) didn't cover 147. 
How should I config my wireshark to decode the pcap?
This is an example [pcap](https://github.com/srsran/srsRAN_4G/files/11541094/npdsch.pcap.zip).
And I confirmed that it worked well with srsGUI.

![Screenshot from 2023-05-23 03-56-17](https://github.com/srsran/srsRAN_4G/assets/38338565/58d7f221-1c3d-420f-a66a-a41213bcaa88)

Thanks in advance!

**Comment by brendan-mcauliffe** [comment]
Hi @VLiu7, 

If you go _Preferences > Protocols > DLT_USER_

You can add an entry with the following details for `DLT=147` to correctly decode the pcap: 

![image](https://github.com/srsran/srsRAN_4G/assets/37801273/5f856328-ffb4-4308-952a-b99d72d36b9c)

(See the highlighted line)

**Comment by VLiu7** [comment]
It works! Thanks a lot!
