### ISSUE TITLE
Does SMS support in lastest SRSRAN 4G?

### ISSUE THREAD

**Issue by hz-nokia** [srsran/srsRAN_4G#1191]
Hello!

Does SMS support in lastest SRSRAN 4G?

**Comment by andrepuschmann** [comment]
I think there it's possible to send SMS over NAS but I've never tried it myself. Maybe someone else can help. Anyway, it's not an issue with the code - so better to move to discussions.

**Comment by hz-nokia** [comment]
hi andre,
   If srsue can send SMS over NAS, we need set SMSC. But I can't find it in code or ue.conf. BTW, I use my smartphone to send a SMS msg to B200, there is no downlink nas transport or CP_DATA in ue.log or nas.pcap.





--
发自我的网易邮箱手机智能版



在 2023-06-30 19:20:31，"Andre Puschmann" ***@***.***> 写道：


I think there it's possible to send SMS over NAS but I've never tried it myself. Maybe someone else can help. Anyway, it's not an issue with the code - so better to move to discussions.
