### ISSUE TITLE
UE is not attaching to eNB

### ISSUE THREAD

**Issue by sruthi81** [srsran/srsRAN_4G#1195]
## Issue Description ##
srsUE is not attaching to srsENB for 5G SA with ADALM Pluto hardware devices

## Setup Details ##
srsUE and srsENB are setup in two seperate machines and to each machine an ADALM Pluto is connected. Open5gs is used as the core network.
## Expected Behavior ##
UE attaches to eNB and ping transfer is possible

## Actual Behaviour ##

UE Console

![ue](https://github.com/srsran/srsRAN_4G/assets/60339500/e9cca31a-97a9-4889-b101-caf106a33e0d)
![ue_2](https://github.com/srsran/srsRAN_4G/assets/60339500/8190e8a3-7782-4556-b221-f60878904897)

eNB Console

![Screenshot from 2023-07-06 16-11-55](https://github.com/srsran/srsRAN_4G/assets/60339500/bfd760b5-7054-4544-977d-7164a4a5dca1)

## Steps to reproduce the problem ##
[ue_conf.txt](https://github.com/srsran/srsRAN_4G/files/11967761/ue_conf.txt)
[enb_conf.txt](https://github.com/srsran/srsRAN_4G/files/11967760/enb_conf.txt)

## Additional Information ##
[ue.log](https://github.com/srsran/srsRAN_4G/files/11967532/ue.log)
[enb.log](https://github.com/srsran/srsRAN_4G/files/11967712/enb.log)

**Comment by andrepuschmann** [comment]
I am not sure this is even possible. The minimum bandwidth for SA is 5 MHz. Sample rate 5.76msps. I don't think the Pluto can even work with this rate over USB2.

**Comment by sruthi81** [comment]
Ok Thankyou Sir.

**Comment by sruthi81** [comment]
i had a doubt the adalp pluto specifications stating that the max sample rate can go to 56 mhz and the band width upto 20 mhz. Then it should work for 5G?
