### ISSUE TITLE
[ERROR] [UHD RF] std::bad_alloc

### ISSUE THREAD

**Issue by stackprogramer** [srsran/srsRAN_4G#1210]
why when start-stop srsenb i faced with a strange error  how can solve this error 
[ERROR] [UHD RF] std::bad_alloc

**Comment by MitraTor** [comment]
I have built a 4G network using srsRAN 4G and USRP B 205 mini. now I want to build the network using USRP X300. After running the command " sudo srsenb enb.conf" I get the same error([ERROR] [UHD RF] std::bad_alloc). Did you solve the error?

**Comment by andrepuschmann** [comment]
Please use the issue template to share the entire setup, library and program versions, configs, output, etc. Otherwise we can't check and help.
