### ISSUE TITLE
Does it support dynamic verification of communication resource allocation algorithms

### ISSUE THREAD

**Issue by LightForever-Lu** [srsran/srsRAN_4G#1232]
## Issue Description ##
I want to verify some online communication resource allocation algorithms based on this platform and USRP. Does this platform support dynamic modification of communication resources such as spectrum, time, power and so on?

## Setup Details ##
Dynamic resource allocation

## Expected Behavior ##
I wanted to find APIs related to dynamic communication resource settings

## Actual Behaviour ##
None

## Steps to reproduce the problem ##
None

## Additional Information ##
None

**Comment by andrepuschmann** [comment]
Your question is not an issue and should rather be put into the discussion group. But the short answer is yes, the Mac scheduler does dynamic time and frequency resource allocation.
