### ISSUE TITLE
Manage 2 usrp b200

### ISSUE THREAD

**Issue by UserMSU** [srsran/srsRAN_4G#1239]
How can I manage 2 USRP B200 from 1 linux system? I see that srsenb detects usrp automatically. But if I connect 2 usrp how it will do that? Should I open 2 terminals and use srsenb with some configs like --~ ?

**Comment by c-aman** [comment]
you need 2 linux system each connected to USRP, one for enb & spc , while other for ue

**Comment by c-aman** [comment]
ohh, I thought its for single enb/ue setup.

But does srsepc have support for multi-enb, because for "srsRAN 4G with ZMQ Virtual Radios" they have written this in the known issues,
"We currently only support a single eNB and a single UE."
