### ISSUE TITLE
Make test got stuck for test 121: pssch_test_tm2_p6

### ISSUE THREAD

**Issue by reallsj** [srsran/srsRAN_4G#1260]
System: Ubuntu 22.04.3 LTS
The previous steps are perfect for me, but when process make test, the 121 test got stuck. The terminal is still running, can anyone help?
ubuntu@sjli:~/srsRAN2/build$ make test
Running tests...
Test project /home/ubuntu/srsRAN2/build
          Start    1: thread_pool_test
   1/1523 Test    #1: thread_pool_test ................................................   Passed    4.14 sec
          Start    2: thread_test
   2/1523 Test    #2: thread_test .....................................................   Passed    0.00 sec
          Start    3: band_helper_test
   3/1523 Test    #3: band_helper_test ................................................   Passed    0.00 sec
          Start    4: pdu_test
   4/1523 Test    #4: pdu_test ........................................................   Passed    0.00 sec
          Start    5: mac_pcap_test
   5/1523 Test    #5: mac_pcap_test ...................................................   Passed    0.01 sec
          Start    6: mac_pdu_nr_test
   6/1523 Test    #6: mac_pdu_nr_test .................................................   Passed    0.00 sec
          Start    7: chest_test_dl_cellid0
   7/1523 Test    #7: chest_test_dl_cellid0 ...........................................   Passed    0.01 sec
          Start    8: chest_test_dl_cellid1
   8/1523 Test    #8: chest_test_dl_cellid1 ...........................................   Passed    0.00 sec
          Start    9: chest_test_dl_cellid2
   9/1523 Test    #9: chest_test_dl_cellid2 ...........................................   Passed    0.00 sec
          Start   10: chest_test_dl_cellid0_50prb
  10/1523 Test   #10: chest_test_dl_cellid0_50prb .....................................   Passed    0.01 sec
          Start   11: chest_test_dl_cellid1_50prb
  11/1523 Test   #11: chest_test_dl_cellid1_50prb .....................................   Passed    0.02 sec
          Start   12: chest_test_dl_cellid2_50prb
  12/1523 Test   #12: chest_test_dl_cellid2_50prb .....................................   Passed    0.01 sec
          Start   13: chest_test_ul_cellid0
  13/1523 Test   #13: chest_test_ul_cellid0 ...........................................   Passed    0.04 sec
          Start   14: chest_test_ul_cellid1
  14/1523 Test   #14: chest_test_ul_cellid1 ...........................................   Passed    0.04 sec
          Start   15: chest_test_ul_cellid2
  15/1523 Test   #15: chest_test_ul_cellid2 ...........................................   Passed    0.04 sec
          Start   16: chest_test_srs_6
  16/1523 Test   #16: chest_test_srs_6 ................................................   Passed    1.25 sec
          Start   17: chest_test_srs_15
  17/1523 Test   #17: chest_test_srs_15 ...............................................   Passed    1.26 sec
          Start   18: chest_test_srs_25
  18/1523 Test   #18: chest_test_srs_25 ...............................................   Passed    1.38 sec
          Start   19: chest_test_srs_50
  19/1523 Test   #19: chest_test_srs_50 ...............................................   Passed    1.31 sec
          Start   20: chest_test_srs_75
  20/1523 Test   #20: chest_test_srs_75 ...............................................   Passed    1.43 sec
          Start   21: chest_test_srs_100
  21/1523 Test   #21: chest_test_srs_100 ..............................................   Passed    1.55 sec
          Start   22: chest_nbiot_test_dl
  22/1523 Test   #22: chest_nbiot_test_dl .............................................   Passed    0.00 sec
          Start   23: chest_test_sl_psbch
  23/1523 Test   #23: chest_test_sl_psbch .............................................   Passed    0.00 sec
          Start   24: dmrs_pdsch_test
  24/1523 Test   #24: dmrs_pdsch_test .................................................   Passed    3.55 sec
          Start   25: dmrs_pdcch_test_non_interleaved
  25/1523 Test   #25: dmrs_pdcch_test_non_interleaved .................................   Passed    2.07 sec
          Start   26: dmrs_pdcch_test_interleaved
  26/1523 Test   #26: dmrs_pdcch_test_interleaved .....................................   Passed    1.48 sec
          Start   27: csi_rs_test
  27/1523 Test   #27: csi_rs_test .....................................................   Passed    0.00 sec
          Start   28: csi_rs_pattern_test
  28/1523 Test   #28: csi_rs_pattern_test .............................................   Passed    0.00 sec
          Start   29: sequence_test
  29/1523 Test   #29: sequence_test ...................................................   Passed    0.01 sec
          Start   30: sliv_test_14
  30/1523 Test   #30: sliv_test_14 ....................................................   Passed    0.00 sec
          Start   31: sliv_test_52
  31/1523 Test   #31: sliv_test_52 ....................................................   Passed    0.00 sec
          Start   32: phy_common_test
  32/1523 Test   #32: phy_common_test .................................................   Passed    0.00 sec
          Start   33: block_test_20
  33/1523 Test   #33: block_test_20 ...................................................   Passed    0.00 sec
          Start   34: block_test_32
  34/1523 Test   #34: block_test_32 ...................................................   Passed    0.00 sec
          Start   35: block_test_48
  35/1523 Test   #35: block_test_48 ...................................................   Passed    0.00 sec
          Start   36: viterbi_40_0
  36/1523 Test   #36: viterbi_40_0 ....................................................   Passed    0.02 sec
          Start   37: viterbi_40_2
  37/1523 Test   #37: viterbi_40_2 ....................................................   Passed    0.02 sec
          Start   38: viterbi_40_3
  38/1523 Test   #38: viterbi_40_3 ....................................................   Passed    0.02 sec
          Start   39: viterbi_40_4
  39/1523 Test   #39: viterbi_40_4 ....................................................   Passed    0.02 sec
          Start   40: viterbi_1000_2
  40/1523 Test   #40: viterbi_1000_2 ..................................................   Passed    0.05 sec
          Start   41: viterbi_1000_3
  41/1523 Test   #41: viterbi_1000_3 ..................................................   Passed    0.04 sec
          Start   42: viterbi_1000_4
  42/1523 Test   #42: viterbi_1000_4 ..................................................   Passed    0.04 sec
          Start   43: viterbi_56_4
  43/1523 Test   #43: viterbi_56_4 ....................................................   Passed    0.03 sec
          Start   44: LDPC-chain
  44/1523 Test   #44: LDPC-chain ......................................................   Passed    1.83 sec
          Start   45: LDPC-RM-chain
  45/1523 Test   #45: LDPC-RM-chain ...................................................   Passed    0.00 sec
          Start   46: polar_interleaver_test
  46/1523 Test   #46: polar_interleaver_test ..........................................   Passed    0.00 sec
          Start   47: crc_24A
  47/1523 Test   #47: crc_24A .........................................................   Passed    0.00 sec
          Start   48: crc_24B
  48/1523 Test   #48: crc_24B .........................................................   Passed    0.00 sec
          Start   49: crc_16
  49/1523 Test   #49: crc_16 ..........................................................   Passed    0.00 sec
          Start   50: crc_8
  50/1523 Test   #50: crc_8 ...........................................................   Passed    0.00 sec
          Start   51: crc_11
  51/1523 Test   #51: crc_11 ..........................................................   Passed    0.00 sec
          Start   52: crc_6
  52/1523 Test   #52: crc_6 ...........................................................   Passed    0.00 sec
          Start   53: rm_conv_test_1
  53/1523 Test   #53: rm_conv_test_1 ..................................................   Passed    0.00 sec
          Start   54: rm_conv_test_2
  54/1523 Test   #54: rm_conv_test_2 ..................................................   Passed    0.00 sec
          Start   55: rm_turbo_test_1
  55/1523 Test   #55: rm_turbo_test_1 .................................................   Passed    0.04 sec
          Start   56: rm_turbo_test_2
  56/1523 Test   #56: rm_turbo_test_2 .................................................   Passed    0.04 sec
          Start   57: turbodecoder_test_504_1
  57/1523 Test   #57: turbodecoder_test_504_1 .........................................   Passed    0.01 sec
          Start   58: turbodecoder_test_504_2
  58/1523 Test   #58: turbodecoder_test_504_2 .........................................   Passed    0.01 sec
          Start   59: turbodecoder_test_6114_1_5
  59/1523 Test   #59: turbodecoder_test_6114_1_5 ......................................   Passed    0.07 sec
          Start   60: turbodecoder_test_known
  60/1523 Test   #60: turbodecoder_test_known .........................................   Passed    0.01 sec
          Start   61: turbocoder_test_all
  61/1523 Test   #61: turbocoder_test_all .............................................   Passed    0.01 sec
          Start   62: layermap_single
  62/1523 Test   #62: layermap_single .................................................   Passed    0.00 sec
          Start   63: layermap_diversity_2
  63/1523 Test   #63: layermap_diversity_2 ............................................   Passed    0.00 sec
          Start   64: layermap_diversity_4
  64/1523 Test   #64: layermap_diversity_4 ............................................   Passed    0.00 sec
          Start   65: layermap_multiplex_11
  65/1523 Test   #65: layermap_multiplex_11 ...........................................   Passed    0.00 sec
          Start   66: layermap_multiplex_12
  66/1523 Test   #66: layermap_multiplex_12 ...........................................   Passed    0.00 sec
          Start   67: layermap_multiplex_13
  67/1523 Test   #67: layermap_multiplex_13 ...........................................   Passed    0.00 sec
          Start   68: layermap_multiplex_14
  68/1523 Test   #68: layermap_multiplex_14 ...........................................   Passed    0.00 sec
          Start   69: layermap_multiplex_22
  69/1523 Test   #69: layermap_multiplex_22 ...........................................   Passed    0.00 sec
          Start   70: layermap_multiplex_23
  70/1523 Test   #70: layermap_multiplex_23 ...........................................   Passed    0.00 sec
          Start   71: layermap_multiplex_24
  71/1523 Test   #71: layermap_multiplex_24 ...........................................   Passed    0.00 sec
          Start   72: precoding_single
  72/1523 Test   #72: precoding_single ................................................   Passed    0.00 sec
          Start   73: precoding_diversity2
  73/1523 Test   #73: precoding_diversity2 ............................................   Passed    0.00 sec
          Start   74: precoding_diversity4
  74/1523 Test   #74: precoding_diversity4 ............................................   Passed    0.00 sec
          Start   75: precoding_cdd_2x2_zf
  75/1523 Test   #75: precoding_cdd_2x2_zf ............................................   Passed    0.01 sec
          Start   76: precoding_cdd_2x2_mmse
  76/1523 Test   #76: precoding_cdd_2x2_mmse ..........................................   Passed    0.00 sec
          Start   77: precoding_multiplex_1l_cb0
  77/1523 Test   #77: precoding_multiplex_1l_cb0 ......................................   Passed    0.00 sec
          Start   78: precoding_multiplex_1l_cb1
  78/1523 Test   #78: precoding_multiplex_1l_cb1 ......................................   Passed    0.01 sec
          Start   79: precoding_multiplex_1l_cb2
  79/1523 Test   #79: precoding_multiplex_1l_cb2 ......................................   Passed    0.01 sec
          Start   80: precoding_multiplex_1l_cb3
  80/1523 Test   #80: precoding_multiplex_1l_cb3 ......................................   Passed    0.01 sec
          Start   81: precoding_multiplex_2l_cb0_zf
  81/1523 Test   #81: precoding_multiplex_2l_cb0_zf ...................................   Passed    0.00 sec
          Start   82: precoding_multiplex_2l_cb1_zf
  82/1523 Test   #82: precoding_multiplex_2l_cb1_zf ...................................   Passed    0.00 sec
          Start   83: precoding_multiplex_2l_cb2_zf
  83/1523 Test   #83: precoding_multiplex_2l_cb2_zf ...................................   Passed    0.01 sec
          Start   84: precoding_multiplex_2l_cb0_mmse
  84/1523 Test   #84: precoding_multiplex_2l_cb0_mmse .................................   Passed    0.00 sec
          Start   85: precoding_multiplex_2l_cb1_mmse
  85/1523 Test   #85: precoding_multiplex_2l_cb1_mmse .................................   Passed    0.00 sec
          Start   86: precoding_multiplex_2l_cb2_mmse
  86/1523 Test   #86: precoding_multiplex_2l_cb2_mmse .................................   Passed    0.00 sec
          Start   87: pmi_select_test
  87/1523 Test   #87: pmi_select_test .................................................   Passed    0.00 sec
          Start   88: pbch_test_6
  88/1523 Test   #88: pbch_test_6 .....................................................   Passed    0.00 sec
          Start   89: pbch_test_62
  89/1523 Test   #89: pbch_test_62 ....................................................   Passed    0.00 sec
          Start   90: pbch_test_64
  90/1523 Test   #90: pbch_test_64 ....................................................   Passed    0.00 sec
          Start   91: pbch_test_50
  91/1523 Test   #91: pbch_test_50 ....................................................   Passed    0.00 sec
          Start   92: pbch_test_502
  92/1523 Test   #92: pbch_test_502 ...................................................   Passed    0.00 sec
          Start   93: pbch_test_504
  93/1523 Test   #93: pbch_test_504 ...................................................   Passed    0.00 sec
          Start   94: psbch_test_self_test_tm2_p6_c168_self
  94/1523 Test   #94: psbch_test_self_test_tm2_p6_c168_self ...........................   Passed    0.00 sec
          Start   95: psbch_test_self_test_tm2_p50_c168_self
  95/1523 Test   #95: psbch_test_self_test_tm2_p50_c168_self ..........................   Passed    0.00 sec
          Start   96: psbch_test_self_test_tm2_p100_c168_self
  96/1523 Test   #96: psbch_test_self_test_tm2_p100_c168_self .........................   Passed    0.00 sec
          Start   97: psbch_test_self_test_tm2_p25_c168_ext_self
  97/1523 Test   #97: psbch_test_self_test_tm2_p25_c168_ext_self ......................   Passed    0.00 sec
          Start   98: psbch_test_self_test_tm2_p100_c335_ext_self
  98/1523 Test   #98: psbch_test_self_test_tm2_p100_c335_ext_self .....................   Passed    0.00 sec
          Start   99: psbch_test_self_test_tm4_p6_c168_self
  99/1523 Test   #99: psbch_test_self_test_tm4_p6_c168_self ...........................   Passed    0.00 sec
          Start  100: psbch_test_self_test_tm4_p50_c168_self
 100/1523 Test  #100: psbch_test_self_test_tm4_p50_c168_self ..........................   Passed    0.00 sec
          Start  101: psbch_test_self_test_tm4_p100_c168_self
 101/1523 Test  #101: psbch_test_self_test_tm4_p100_c168_self .........................   Passed    0.00 sec
          Start  102: psbch_file_test_ideal_tm2_p6_c0
 102/1523 Test  #102: psbch_file_test_ideal_tm2_p6_c0 .................................   Passed    0.00 sec
          Start  103: psbch_file_test_ideal_tm2_p15_c84
 103/1523 Test  #103: psbch_file_test_ideal_tm2_p15_c84 ...............................   Passed    0.00 sec
          Start  104: psbch_file_test_ideal_tm2_p25_c168
 104/1523 Test  #104: psbch_file_test_ideal_tm2_p25_c168 ..............................   Passed    0.00 sec
          Start  105: psbch_file_test_ideal_tm2_p50_c252
 105/1523 Test  #105: psbch_file_test_ideal_tm2_p50_c252 ..............................   Passed    0.00 sec
          Start  106: psbch_file_test_ideal_tm2_p100_c335
 106/1523 Test  #106: psbch_file_test_ideal_tm2_p100_c335 .............................   Passed    0.00 sec
          Start  107: psbch_file_test_ideal_tm2_p50_c252_ext
 107/1523 Test  #107: psbch_file_test_ideal_tm2_p50_c252_ext ..........................   Passed    0.00 sec
          Start  108: psbch_file_test_cmw_tm4_p50_c169
 108/1523 Test  #108: psbch_file_test_cmw_tm4_p50_c169 ................................   Passed    0.00 sec
          Start  109: pscch_test_tm2_p6
 109/1523 Test  #109: pscch_test_tm2_p6 ...............................................   Passed    0.00 sec
          Start  110: pscch_test_tm2_p15
 110/1523 Test  #110: pscch_test_tm2_p15 ..............................................   Passed    0.00 sec
          Start  111: pscch_test_tm2_p25
 111/1523 Test  #111: pscch_test_tm2_p25 ..............................................   Passed    0.00 sec
          Start  112: pscch_test_tm2_p50
 112/1523 Test  #112: pscch_test_tm2_p50 ..............................................   Passed    0.00 sec
          Start  113: pscch_test_tm2_p75
 113/1523 Test  #113: pscch_test_tm2_p75 ..............................................   Passed    0.00 sec
          Start  114: pscch_test_tm2_p100
 114/1523 Test  #114: pscch_test_tm2_p100 .............................................   Passed    0.00 sec
          Start  115: pscch_test_tm4_p6
 115/1523 Test  #115: pscch_test_tm4_p6 ...............................................   Passed    0.00 sec
          Start  116: pscch_test_tm4_p15
 116/1523 Test  #116: pscch_test_tm4_p15 ..............................................   Passed    0.00 sec
          Start  117: pscch_test_tm4_p25
 117/1523 Test  #117: pscch_test_tm4_p25 ..............................................   Passed    0.00 sec
          Start  118: pscch_test_tm4_p50
 118/1523 Test  #118: pscch_test_tm4_p50 ..............................................   Passed    0.00 sec
          Start  119: pscch_test_tm4_p75
 119/1523 Test  #119: pscch_test_tm4_p75 ..............................................   Passed    0.00 sec
          Start  120: pscch_test_tm4_p100
 120/1523 Test  #120: pscch_test_tm4_p100 .............................................   Passed    0.00 sec
          Start  121: pssch_test_tm2_p6

**Comment by tilldroemmer** [comment]
@reallsj I noticed you closed the issue, how did you solve it? I am stuck at the same test

**Comment by reallsj** [comment]
> @reallsj I noticed you closed the issue, how did you solve it? I am stuck at the same test

Just wait it to move on, dont close the terminal.
