### ISSUE TITLE
Error with UE and eNodeB

### ISSUE THREAD

**Issue by AbdoRaheel** [srsran/srsRAN_4G#1266]
## Issue Description ##
[When running srsue and srsenb it gives those errors although it run srsepc ]

## Setup Details ##
[2PCs each connected to usrpX310 which are connected to each other by RF cables and 30db attenuator with ubuntu 22.04 and UHD 4.1.0]

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[
![Screenshot 2024-01-09 180506](https://github.com/srsran/srsRAN_4G/assets/132466266/c5ecc91b-8dca-4eba-8401-95517c7e7991)
![Screenshot 2024-01-09 180541](https://github.com/srsran/srsRAN_4G/assets/132466266/f2db74fc-3576-4d85-a4c4-88b85fa62c59)
]

**Comment by andrepuschmann** [comment]
Seems like you have compiled without UHD support.
