### ISSUE TITLE
UECapabilityEnquiry question change content and query add rat-Type

### ISSUE THREAD

**Issue by cosmicDustOfLightLength** [srsran/srsRAN_4G#1270]
## Issue Description ##
Is there any way to modify the query "UECapabilityEnquiry" sent to the UE?
Or is it possible to enter hex rrc.dl.dcch somewhere to send a query to the UE?

## Additional Information ##
https://www.sharetechnote.com/html/Handbook_LTE_UE_Capability.html

**Comment by andrepuschmann** [comment]
You can of course modify the code to send whatever you want to the UE. I suggest you study the RRC code inside the enb.
