### ISSUE TITLE
Cannot modify the code in main.cc

### ISSUE THREAD

**Issue by reallsj** [srsran/srsRAN_4G#1271]
## Issue Description ##
I changed the code in main.cc file inside the srsenb, and complied it using cmake, but when I execute the program using command srsenb, nothing changed. I checked whether something went wrong with cmake, so I changed something inside the cell_search.c, and it worked perfectly. Please help.

## Setup Details ##
Ubuntu 22.04 LTS

## Expected Behavior ##
After compiling, the program should change, I experimented with very simple printf but it didnt work.

## Actual Behaviour ##
Nothing changed

**Comment by andrepuschmann** [comment]
This is not an srsRAN issue. Closing.
