### ISSUE TITLE
nr_sa_cell_search_test not working on mode 2

### ISSUE THREAD

**Issue by liming2354** [srsran/srsRAN_4G#1277]
## Issue Description ##
I try running the nr_sa_cell_search_test  on mode 2 but theres nothing output
## Setup Details ##
Debian9
gcc 6.3.0
latest srsRAN release 23.11

## Expected Behavior ##
i expected to get a list of available cells and their earfcns

## Actual Behaviour ##
/home/bluewater/srsRAN/srsRAN_4G-release_23_11/build_debug/srsue/src/phy/test# ./nr_sa_cell_search_test --sim.pci_list=52
Skipping RF plugin libsrsran_rf_zmq.so: libsrsran_rf_zmq.so: cannot open shared object file: No such file or directory
Active RF plugins:
Inactive RF plugins: libsrsran_rf_zmq.so

## Steps to reproduce the problem ##
run the /home/bluewater/srsRAN/srsRAN_4G-release_23_11/build_debug/srsue/src/phy/test# ./nr_sa_cell_search_test --sim.pci_list=52
ANy feedback will be great!

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by andrepuschmann** [comment]
I assume you want to scan real cells, do you? If so, you have to compile with RF support.
