### ISSUE TITLE
NB-IoT setup using ZMQ error

### ISSUE THREAD

**Issue by ahmedelbushra** [srsran/srsRAN_4G#1298]
## Issue Description ##
I tried to detect the cell of enb using (**cell_search_nbiot**, and **npdsch_ue**) within the zmq environment, the issue that I am facing is that **cell_search_nbiot** and **npdsch_ue** detect the wrong cell (cell ID) and the graph I am getting from srsGUI makes no sense. how can I get the expect graph and cell ID. The cell expected to be found should be (CELL ID = 1) but it detect (CELL ID = 39)

## Setup Details ##
step 1: run epc ( **sudo ./srsepc/src/srsepc**).
step 2: run enb ( **./srsenb/src/srsenb --rf.device_name=zmq --rf.device_args="fail_on_disconnect=true,tx_port=tcp://*:2000,rx_port=tcp://localhost:2001,id=enb,base_srate=23.04e6"** ) 
![Screenshot from 2024-03-08 20-53-41](https://github.com/srsran/srsRAN_4G/assets/72094356/ec4092b7-144c-40a4-93c2-0bc4a3871716)
step 3 : run cell search ( **./cell_search_nbiot -b 7 -a "tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6"** )
The cell search found the cell in 2626.3 MHz.
 
step 4 : run npdsh_ue ( **sudo ./npdsch_ue -f 2626.3e6  -I zmq -a "tx_port=tcp://*:2001,rx_port=tcp://localhost:2000,id=ue,base_srate=23.04e6"**)
![Screenshot from 2024-03-08 20-57-30](https://github.com/srsran/srsRAN_4G/assets/72094356/0a4f82ab-2994-4178-845b-59fb5685fac2)
![Screenshot from 2024-03-08 20-58-07](https://github.com/srsran/srsRAN_4G/assets/72094356/9023b0ad-4c6a-4d8d-9ae7-587e53f5d8a5)
file:///home/system0/Pictures/Screenshots/Screenshot%20from%202024-03-08%2020-58-40.png

## Expected Behavior ##
My expectation is to get something similar to https://docs.srsran.com/projects/4g/en/latest/app_notes/source/nbiot/source/index.html

**Comment by andrepuschmann** [comment]
Hey, 
what you're trying to do will not work. The NB-IoT examples aren't compatible with the LTE eNodeB. Only `npdsche_enodeb` and `npdsch_ue` will work together. You can also use the cell search example to find commercial NB-IoT cells. Hope that helps.
