### ISSUE TITLE
decoding using npdsch_ue failed 

### ISSUE THREAD

**Issue by ahmedelbushra** [srsran/srsRAN_4G#1299]
## Issue Description ##
I am using RTL-SDR to detect and decode NB-IoT, I was able to detect but not decode it.

## Setup Details ##
step1: run ./cell_search_nbiot -b 20 
![Screenshot from 2024-03-12 16-17-28](https://github.com/srsran/srsRAN_4G/assets/72094356/c8a9258d-7654-4af1-9699-46dfc35dc237)

step2: ./npdsch_ue -f 815.9e6 
![Screenshot from 2024-03-12 16-19-00](https://github.com/srsran/srsRAN_4G/assets/72094356/170c906b-5ee5-4669-830a-2077eac18463)

## Expected Behavior ##
![image](https://github.com/srsran/srsRAN_4G/assets/72094356/f1028033-fa2c-4af1-a312-fc679f944d48)

## Actual Behavior ##
![Screenshot from 2024-03-12 16-21-30](https://github.com/srsran/srsRAN_4G/assets/72094356/b8f5042f-0073-46d5-824e-6a6f9a0b5051)

**Comment by andrepuschmann** [comment]
The cell ID detection might not work super reliably depending on your RF situation. Have you verified there is an NB-IoT carrier at all in on that frequency? You can do that with any spectrum monitoring app.

**Comment by ahmedelbushra** [comment]
I am RTL SDR Gqrx to view the spectrum : the cell_search_nbiot  detected 2 cells,
![Screenshot from 2024-03-13 12-14-59](https://github.com/srsran/srsRAN_4G/assets/72094356/0c1472aa-0a29-4c8c-aeb1-402ad82871e3)
The output of the Gqrx : 
![Screenshot from 2024-03-13 12-16-32](https://github.com/srsran/srsRAN_4G/assets/72094356/d0520b2a-65f1-4108-807a-3710fc9c774c)
It show no signals in that range.

**Comment by andrepuschmann** [comment]
Hard to say if there is an NB-IoT carrier at all. The NPSS power is very low, too low to reliably sync on it anyway. Maybe try to get closer to the cell. See [here](https://docs.srsran.com/projects/4g/en/latest/app_notes/source/nbiot/source/index.html) how the spectrum should look like.
