### ISSUE TITLE
UE cannot find the LTE Network

### ISSUE THREAD

**Issue by fiveheadShinchan** [srsran/srsRAN_4G#1342]
## Issue Description ##

I have followed the directions from the website: https://lists.srsran.com/mailman/listinfo/srsran-users
I have tried changing the EARFCN value to 3350, nof_prb to 25 and 50, and I have also checked the configuration files. I have also read similar tickets and the troubleshoot as well. 

## Setup Details ##

I am using an Oracle VM Virtual box running with DragonOS Focal (20.04) are out-of-the-box Lubuntu based x86_64 operating systems. I have allocated plenty of storage and 8 processors. 

I am using an Ettus 2450 antennas, USRP B210 with the GPSDO activated with external power the LED light is stable, I am using an open cell programmable SIM card with Pixel 3 XR phone. 

sudo srsepc
![image](https://github.com/srsran/srsRAN_4G/assets/109051793/3caf6eb5-799c-480a-bf36-9a1fbb99f2e4)

sudo srsenb
![image](https://github.com/srsran/srsRAN_4G/assets/109051793/c861e28d-2472-45b0-b69c-1330f9f2954a)

![image](https://github.com/srsran/srsRAN_4G/assets/109051793/84c39bcd-434a-434e-8e57-17d4d6e47d96)

![image](https://github.com/srsran/srsRAN_4G/assets/109051793/a2791306-d23e-4438-a870-bb1d6f5665b6)

epc configuration file
![image](https://github.com/srsran/srsRAN_4G/assets/109051793/3d0436c3-5cde-4a63-af72-6494e36680a2)

enb configuration file
![image](https://github.com/srsran/srsRAN_4G/assets/109051793/60d5dc45-9391-4225-a464-26464a4756d9)

user_db.csv file 
![image](https://github.com/srsran/srsRAN_4G/assets/109051793/82c26d4b-779e-4b7e-832e-5dfd9fa7090b)

## Expected Behavior ##
UE is able to find the network when looking for network operators

## Actual Behavior ##
UE is not able to see the network that was set up.

**Comment by andrepuschmann** [comment]
It's not straight-forward run timing critical workloads out of a VM. The lates you see are likely causing the UE to not see the cell and thus it can't connect. I suggest you install bare-metal instead.

**Comment by fiveheadShinchan** [comment]
Hello,

Thank you for the quick response. I was wondering if it was not possible to
run on vm. I actually ended up using the wrong USRP B210, without the GPSDO
attached. When I attached the one with GPSDO, I only  got lates of 5-7. The
UE is still not able to find the network.
