### ISSUE TITLE
srsRAN_4G fails to build 

### ISSUE THREAD

**Issue by lingyan98** [srsran/srsRAN_4G#1357]
## Issue Description ##
when I build this project with ubuntu 22.04 and gcc 11. I got the following error:
(base) bly@bly:~/Project/Research/ORAN/srsRAN_4G/build$ make
Consolidate compiler generated dependencies of target srsran_asn1
[  1%] Built target srsran_asn1
Consolidate compiler generated dependencies of target support
[  1%] Built target support
-- Generating build_info.h
[  1%] Built target gen_build_info
Consolidate compiler generated dependencies of target srsran_cfr
[  1%] Built target srsran_cfr
Consolidate compiler generated dependencies of target srsran_agc
[  1%] Built target srsran_agc
Consolidate compiler generated dependencies of target srsran_ch_estimation
[  3%] Built target srsran_ch_estimation
Consolidate compiler generated dependencies of target srsran_phy_common
[  4%] Built target srsran_phy_common
Consolidate compiler generated dependencies of target srsran_fec
[  8%] Built target srsran_fec
Consolidate compiler generated dependencies of target srsran_mimo
[  9%] Built target srsran_mimo
Consolidate compiler generated dependencies of target srsran_phch
[ 13%] Built target srsran_phch
Consolidate compiler generated dependencies of target srsran_sync
[ 14%] Built target srsran_sync
Consolidate compiler generated dependencies of target srsran_utils
[ 15%] Built target srsran_utils
Consolidate compiler generated dependencies of target srsran_channel
[ 15%] Built target srsran_channel
Consolidate compiler generated dependencies of target srsran_dft
[ 15%] Built target srsran_dft
Consolidate compiler generated dependencies of target srsran_io
[ 16%] Built target srsran_io
Consolidate compiler generated dependencies of target srsran_modem
[ 16%] Built target srsran_modem
Consolidate compiler generated dependencies of target srsran_resampling
[ 16%] Built target srsran_resampling
Consolidate compiler generated dependencies of target srsran_scrambling
[ 17%] Built target srsran_scrambling
Consolidate compiler generated dependencies of target srsran_ue
[ 18%] Built target srsran_ue
Consolidate compiler generated dependencies of target srsran_enb
[ 19%] Built target srsran_enb
Consolidate compiler generated dependencies of target srsran_gnb
[ 19%] Built target srsran_gnb
[ 19%] Built target srsran_phy
Consolidate compiler generated dependencies of target srslog
[ 19%] Building CXX object lib/src/srslog/CMakeFiles/srslog.dir/bundled/fmt/format.cc.o
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:71:36: error: ‘dynamic_arg_list’ was not declared in this scope
   71 |   using type = std::array<uint8_t, dynamic_arg_list::max_pool_node_size + 1>;
      |                                    ^~~~~~~~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:71:76: error: template argument 2 is invalid
   71 |   using type = std::array<uint8_t, dynamic_arg_list::max_pool_node_size + 1>;
      |                                                                            ^
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:123:8: error: ‘vector’ in namespace ‘std’ does not name a template type
  123 |   std::vector<type> pool;
      |        ^~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:10:1: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
    9 | #include <mutex>
  +++ |+#include <vector>
   10 | 
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:124:8: error: ‘vector’ in namespace ‘std’ does not name a template type
  124 |   std::vector<uint8_t *> free_list;
      |        ^~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:124:3: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
  124 |   std::vector<uint8_t *> free_list;
      |   ^~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc: In constructor ‘fmt::v9::detail::dyn_node_pool::dyn_node_pool()’:
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:75:5: error: ‘pool’ was not declared in this scope; did you mean ‘powl’?
   75 |     pool.resize(NODE_POOL_SIZE);
      |     ^~~~
      |     powl
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:76:5: error: ‘free_list’ was not declared in this scope
   76 |     free_list.reserve(NODE_POOL_SIZE);
      |     ^~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc: In member function ‘void* fmt::v9::detail::dyn_node_pool::alloc(std::size_t)’:
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:88:18: error: ‘dynamic_arg_list’ has not been declared
   88 |     assert(sz <= dynamic_arg_list::max_pool_node_size && "Object is too large to fit in the pool");
      |                  ^~~~~~~~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:88:5: error: ‘assert’ was not declared in this scope
   88 |     assert(sz <= dynamic_arg_list::max_pool_node_size && "Object is too large to fit in the pool");
      |     ^~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:10:1: note: ‘assert’ is defined in header ‘<cassert>’; did you forget to ‘#include <cassert>’?
    9 | #include <mutex>
  +++ |+#include <cassert>
   10 | 
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:91:9: error: ‘free_list’ was not declared in this scope
   91 |     if (free_list.empty()) {
      |         ^~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:94:11: error: invalid types ‘fmt::v9::detail::type[int]’ for array subscript
   94 |       (*p)[0] = memory_heap_tag;
      |           ^
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:95:17: error: request for member ‘data’ in ‘* p’, which is of non-class type ‘fmt::v9::detail::type’
   95 |       return p->data() + 1;
      |                 ^~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:98:15: error: ‘free_list’ was not declared in this scope
   98 |     auto* p = free_list.back();
      |               ^~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc: In member function ‘void fmt::v9::detail::dyn_node_pool::dealloc(void*)’:
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:119:5: error: ‘free_list’ was not declared in this scope
  119 |     free_list.push_back(base_ptr);
      |     ^~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc: At global scope:
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:130:7: error: ‘dynamic_arg_list’ has not been declared
  130 | void *dynamic_arg_list::allocate_from_pool(std::size_t sz) {
      |       ^~~~~~~~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:134:6: error: ‘dynamic_arg_list’ has not been declared
  134 | void dynamic_arg_list::free_from_pool(void *ptr) {
      |      ^~~~~~~~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:140:67: error: invalid declarator before ‘;’ token
  140 | template struct FMT_INSTANTIATION_DEF_API detail::basic_data<void>;
      |                                                                   ^
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:153:38: error: ‘fmt::v9::detail::grouping_impl’ should have been declared inside ‘fmt::v9::detail’
  153 | template FMT_API std::string detail::grouping_impl<char>(locale_ref);
      |                                      ^~~~~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:153:38: error: ‘grouping_impl’ is not a template function
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:153:51: error: expected ‘;’ before ‘<’ token
  153 | template FMT_API std::string detail::grouping_impl<char>(locale_ref);
      |                                                   ^
      |                                                   ;
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:154:23: error: template-id ‘thousands_sep_impl<>’ for ‘char fmt::v9::detail::thousands_sep_impl(fmt::v9::detail::locale_ref)’ does not match any template declaration
  154 | template FMT_API char detail::thousands_sep_impl(locale_ref);
      |                       ^~~~~~
In file included from /home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:8:
/home/bly/anaconda3/include/fmt/format-inl.h:99:15: note: candidate is: ‘template<class Char> fmt::v9::detail::thousands_sep_result<Char> fmt::v9::detail::thousands_sep_impl(fmt::v9::detail::locale_ref)’
   99 | FMT_FUNC auto thousands_sep_impl(locale_ref loc) -> thousands_sep_result<Char> {
      |               ^~~~~~~~~~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:159:53: error: template-id ‘vformat_to<>’ for ‘fmt::v9::basic_format_context<fmt::v9::appender, char>::iterator fmt::v9::detail::vformat_to(fmt::v9::detail::buffer<char>&, fmt::v9::string_view, fmt::v9::basic_format_args<fmt::v9::basic_format_context<fmt::v9::appender, char> >)’ does not match any template declaration
  159 | template FMT_API FMT_BUFFER_CONTEXT(char)::iterator detail::vformat_to(
      |                                                     ^~~~~~
In file included from /home/bly/anaconda3/include/fmt/format-inl.h:29,
                 from /home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:8:
/home/bly/anaconda3/include/fmt/format.h:4056:6: note: candidate is: ‘template<class Char> void fmt::v9::detail::vformat_to(fmt::v9::detail::buffer<T>&, fmt::v9::basic_string_view<Char>, fmt::v9::basic_format_args<fmt::v9::basic_format_context<typename std::conditional<std::is_same<typename fmt::v9::type_identity<T>::type, char>::value, fmt::v9::appender, std::back_insert_iterator<fmt::v9::detail::buffer<typename fmt::v9::type_identity<T>::type> > >::type, typename fmt::v9::type_identity<T>::type> >, fmt::v9::detail::locale_ref)’
 4056 | void vformat_to(
      |      ^~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:175:38: error: ‘fmt::v9::detail::grouping_impl’ should have been declared inside ‘fmt::v9::detail’
  175 | template FMT_API std::string detail::grouping_impl<wchar_t>(locale_ref);
      |                                      ^~~~~~~~~~~~~
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:175:38: error: ‘grouping_impl’ is not a template function
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:175:51: error: expected ‘;’ before ‘<’ token
  175 | template FMT_API std::string detail::grouping_impl<wchar_t>(locale_ref);
      |                                                   ^
      |                                                   ;
/home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:176:26: error: template-id ‘thousands_sep_impl<>’ for ‘wchar_t fmt::v9::detail::thousands_sep_impl(fmt::v9::detail::locale_ref)’ does not match any template declaration
  176 | template FMT_API wchar_t detail::thousands_sep_impl(locale_ref);
      |                          ^~~~~~
In file included from /home/bly/Project/Research/ORAN/srsRAN_4G/lib/src/srslog/bundled/fmt/format.cc:8:
/home/bly/anaconda3/include/fmt/format-inl.h:99:15: note: candidate is: ‘template<class Char> fmt::v9::detail::thousands_sep_result<Char> fmt::v9::detail::thousands_sep_impl(fmt::v9::detail::locale_ref)’
   99 | FMT_FUNC auto thousands_sep_impl(locale_ref loc) -> thousands_sep_result<Char> {
      |               ^~~~~~~~~~~~~~~~~~
make[2]: *** [lib/src/srslog/CMakeFiles/srslog.dir/build.make:132: lib/src/srslog/CMakeFiles/srslog.dir/bundled/fmt/format.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8033: lib/src/srslog/CMakeFiles/srslog.dir/all] Error 2
make: *** [Makefile:166: all] Error 2

**Comment by Rango-T10000** [comment]
Please use "conda deactivate" first to exit anaconda. And then Try again.
