### ISSUE TITLE
Downlink NAS: Sending Authentication Request UL NAS: Authentication Failure MAC code failure

### ISSUE THREAD

**Issue by thisisbaskara** [srsran/srsRAN_4G#1371]
Hey everyone,

I'm encountering an authentication issue with my cellphone when connecting to the srsRAN_4G network. As I'm getting 
Downlink NAS: Sending Authentication Request
UL NAS: Authentication Failure
MAC code failure. 
I also have captured a snapshot from srsepc side for reference.
![MAC CODE FAILURE](https://github.com/user-attachments/assets/085787c6-364f-441f-85e1-230ab349fa74)

These are the files from EPC, ENB, and user_db. I have uploaded them here as a .txt file.
[ENB CONFIG.txt](https://github.com/user-attachments/files/16561828/ENB.CONFIG.txt)
[EPC CONFIG.txt](https://github.com/user-attachments/files/16561829/EPC.CONFIG.txt)
[user_db.csv](https://github.com/user-attachments/files/16561845/user_db.csv)

Currently, I have set up srsRAN 23.04 on an Ubuntu 22.04 desktop, using a blank white sim card from AliExpress, along with a USRP B210 for the eNodeB, and a cellphone. Here are the details from my sim card:
IMSI= 001010000000101
KI= DEAF0FF1CED0D0DABBEDD1CED1CEF00D
OPC= CEDEDEFFACEDACEFACEDBADFADEDBEEF

I have been trying to resolve this issue for the past month since I installed it. 
If anyone could assist in resolving the problem, I would greatly appreciate it. Thank you and best regards.

**Comment by NanFengLi** [comment]
how to solve this problem?
