### ISSUE TITLE
Support for LTE B66?

### ISSUE THREAD

**Issue by dnelson82** [srsran/srsRAN_4G#412]
Before filing an issue, search for solutions here:
- srsLTE users mailing list (http://www.softwareradiosystems.com/mailman/listinfo/srslte-users)

## Issue Description ##
When configuring `srsenb` with the DL EARFCN 66886, a B66 EARFCN, the console message shows `Setting frequency: DL=2155.0 Mhz, UL=2065.0 Mhz`.  The DL frequency is correct but the UL frequency is incorrect as it should be 1755.0 Mhz.  I am able to see the DL transmission on 2155.0 Mhz but no other device can sees the transmission as a valid ENB carrier. Does the latest release of `srsenb` support ENB transmission in LTE band 66 and has it been validated? 

`user@linux:~$ **sudo srsenb --rf.dl_earfcn 66886**

Built in RelWithDebInfo mode using 19.6.0.

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /home/user/.config/srslte/enb.conf...
Opening 1 RF devices with 1 RF channels...
[INFO] [UHD] linux; GNU C++ version 8.2.0; Boost_106700; UHD_3.13.1.0-3
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP with args: type=b200,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Setting frequency: DL=2155.0 Mhz, **UL=2065.0 MHz**
Setting Sampling frequency 11.52 MHz
The condition lb <= n <= ub (1 <= 66 <= 64) was not met
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20093] Encoding failure.
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20393] Encoding failure.
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20273] Encoding failure.
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20423] Encoding failure.

==== eNodeB started ===
Type <t> to view trace`

I also tried setting the DL and UL EARFCN directly but encounter the same issue:

`user@linux:~$ **sudo srsenb --rf.dl_earfcn 66886 --rf.ul_earfcn 132422**

Built in RelWithDebInfo mode using 19.6.0.

---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /home/user/.config/srslte/enb.conf...
Opening 1 RF devices with 1 RF channels...
[INFO] [UHD] linux; GNU C++ version 8.2.0; Boost_106700; UHD_3.13.1.0-3
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP with args: type=b200,master_clock_rate=23.04e6
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Setting frequency: DL=2155.0 Mhz, **UL=2065.0 MHz**
Setting Sampling frequency 11.52 MHz
The condition lb <= n <= ub (1 <= 66 <= 64) was not met
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20093] Encoding failure.
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20393] Encoding failure.
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20273] Encoding failure.
[/build/srslte-ttj7IH/srslte-19.06/lib/src/asn1/rrc_asn1.cc][20423] Encoding failure.

==== eNodeB started ===
Type <t> to view trace`

I also tried setting the UL and DL frequency with the console output showing the frequencies as
`Setting frequency: DL=0.0 Mhz, UL=0.0 MHz`

I configured the `srsenb` for a B30 DL EARFCN and the frequencies are calculated correctly.

## Setup Details ##
I am running the latest release of `srsepc` and `srsenb` on a local Ubuntu 19.04 LTS OS  with an attached USRP B210 using UHD_3.13.1.0-3.

## Expected Behavior ##
The `srsenb` transmitting a LTE B66 carrier that is visible to a UE.

## Actual Behaviour ##
`srsenb` indicates it is transmitting a LTE carrier but the frequencies do not match what is expected

## Steps to reproduce the problem ##

In `~/.conf/enb.conf`, set `dl_earfcn` to 66886
Run `sudo srsenb`
See console output for `Setting frequency` and that the UL frequency is incorrect.

## Additional Information ##
Based on the this output `The condition lb <= n <= ub (1 <= 66 <= 64) was not met`, do I assume that the highest LTE band supported is 64?

**Comment by codershiyar** [comment]
Is there any solution for this problem ?

**Comment by ismagom** [comment]
Unfortunately that band is not supported

**Comment by codershiyar** [comment]
why not? hope you can answer me, thanks in advanced

**Comment by codershiyar** [comment]
Is there any updates or fixes related to Band 66 support since this thread was opened? Or maybe some configuration tips that might help?

Any clarification would be very helpful. Thanks in advance!    

@ismagom @dnelson82 @frankist  @andrepuschmann
