### ISSUE TITLE
Failed to find device auto with args auto

### ISSUE THREAD

**Issue by golisrikanth1989** [srsran/srsRAN_4G#432]
Before filing an issue, search for solutions here:
- srsLTE users mailing list (http://www.softwareradiosystems.com/mailman/listinfo/srslte-users)

## Issue Description ##
Actually trying out the EPC and eNodeB setup with the B210. For installation, I followed the github
srsLTE procedure. But while running the eNodeB, I have some errors like

**Current sample rate is 1.92 MHz with a base rate of 23.04 MHz (x12 decimation)
[zmq] zmq Tx port not specified. Disabling transmitter.
[zmq] zmq Rx port not specified. Disabling receiver.
[zmq] Error: Neither Tx port nor Rx port specified.**

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
Just Installed the srsLTE using github procedure and connected the USRP B210. After which, I tried to run the EPC and eNodeB. 

## Expected Behavior ##
[What you expect to happen]

## Actual Behaviour ##
[What happens instead e.g. error message]

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by ismagom** [comment]
The USRP driver is not correctly installed or not detected by cmake. Follow the instructions in the documentation.
