### ISSUE TITLE
Minimum RSRP Level -101dBm_srsLTE UE

### ISSUE THREAD

**Issue by Vipin2021** [srsran/srsRAN_4G#608]
## Issue Description ##
Observed Minimum RSRP Level for srsLTE UE is around -101dBm, which is quite low and impacting effective coverage area.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
e.g. Network configuration, Operation System, Hardware, RF front-end, library and driver versions
SW : 20.04
X300 + UBX40
UHD : 3.9.7

## Expected Behavior ##
[What you expect to happen]
Need Minimum RSRP Level should be at -120dBm

## Actual Behaviour ##
[What happens instead e.g. error message]
Radio Link Failure as soon as RSRP drops below -101dBm ( +/- 2dBm)

## Steps to reproduce the problem ##
[Tell us how to reproduce this issue e.g. RF setup, application config files]
Just keep on attenuating your RF signal from serving cell

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by jfreivald** [comment]
Noise floor on a 20MHz channel is going to be roughly -101.8 dBm. A 1.4 MHz channel runs at around -114dBm.

Why do you expect an RSRP of -120 to maintain signal lock?
