### ISSUE TITLE
end to end connection between x310(RF Front end)  B210(handset) not happening.

### ISSUE THREAD

**Issue by JCK-1096** [srsran/srsRAN_4G#655]
## Issue Description ##
I am trying to establish an end to end connection, using x310 ( as RF Front end ) at enb side and B210 ( as handset ) at UE side.  
EPC and enb are succesfully launching.
UE is connecting to enb, but UE attach is not happening at EPC side.   
1. Ping 172.16.0.2 is also not happening from UE side. 
2. How to check if tun_srsue virtual network interface is created?  
3. Does the issue lie with using x310 at one end and B210 at other end? 
4. Is this issue related to transmit power levels? since using different USRP's

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
1. sudo apt-get install cmake libfftw3-dev libmbedtls-dev libboost-program-options-dev libconfig++-dev libsctp-dev 
2. install UHD libraries 
3. Download and build srsLTE from github
4. sudo make install
5. srslte_install_configs.sh user
6. running with default settings, IMSI value is same at ue.conf ( machine 1 ) and user_db.csv ( machine 2 )
7. launching sudo srsepc from  /etc/srslte directory from machine 1 : successful launch 
8. launching sudo srsenb from /etc/srslte directory from machine 1 : successful launch 
9. launching sudo srsue from machine 2: able to launch without any errors. 

## Expected Behavior ##
[What you expect to happen]
After launching srsue, RRC connection should happen and attach should happen at srsepc

## Actual Behaviour ##
[What happens instead e.g. error message] 
1. sudo srsepc: 
---  Software Radio Systems EPC  ---

Reading configuration file /etc/srslte/epc.conf...
HSS Initialized.
MME S11 Initialized
MME GTP-C Initialized
MME Initialized. MCC: 0xf001, MNC: 0xff01
SPGW GTP-U Initialized.
SPGW S11 Initialized.
SP-GW Initialized.
Received S1 Setup Request.
S1 Setup Request - eNB Name: srsenb01, eNB id: 0x19b
S1 Setup Request - MCC:001, MNC:01
S1 Setup Request - TAC 7, B-PLMN 0xf110
S1 Setup Request - Paging DRX v128
Sending S1 Setup Response

2. sudo srsenb: 
---  Software Radio Systems LTE eNodeB  ---

Reading configuration file /etc/srslte/enb.conf...
WARNING: cpu0 scaling governor is not set to performance mode. Realtime processing could be compromised. Consider setting it to performance mode before running the application.

Built in Release mode using commit 45486b6e2 on branch master.

Opening 1 channels in RF device=default with args=default
[INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_107100; UHD_3.15.0.0-release
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=x300,master_clock_rate=184.32e6
[INFO] [X300] X300 initialization sequence...
[INFO] [X300] Maximum frame size: 1472 bytes.
[INFO] [X300] Radio 1x clock: 184.32 MHz
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[INFO] [0/DmaFIFO_0] Initializing block control (NOC ID: 0xF1F0D00000000000)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1305 MB/s)
[INFO] [0/DmaFIFO_0] BIST passed (Throughput: 1307 MB/s)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[INFO] [0/Radio_0] Initializing block control (NOC ID: 0x12AD100000000001)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[INFO] [0/Radio_1] Initializing block control (NOC ID: 0x12AD100000000001)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[INFO] [0/DDC_0] Initializing block control (NOC ID: 0xDDC0000000000000)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[INFO] [0/DDC_1] Initializing block control (NOC ID: 0xDDC0000000000000)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[INFO] [0/DUC_0] Initializing block control (NOC ID: 0xD0C0000000000000)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[INFO] [0/DUC_1] Initializing block control (NOC ID: 0xD0C0000000000000)
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
[WARNING] [UDP] The send buffer could not be resized sufficiently.
Target sock buff size: 2426666 bytes.
Actual sock buff size: 1048576 bytes.
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
Setting frequency: DL=2680.0 Mhz, UL=2560.0 MHz for cc_idx=0

==== eNodeB started ===
Type <t> to view trace

3. sudo srsue from machine 2: 
![image](https://user-images.githubusercontent.com/70588262/115879599-d6ce9d00-a417-11eb-9c9e-1c2819b4f238.png)
 
4. Output at UE ( machine 2 ) console: 
![image](https://user-images.githubusercontent.com/70588262/115879760-02ea1e00-a418-11eb-875a-ebcd444d9dd9.png)

5. Output at enb ( Machine 1) console, after UE connects to enb: 

![image](https://user-images.githubusercontent.com/70588262/115879905-28772780-a418-11eb-9397-35595666f468.png)

6. Output at EPC side:  UE attach not happening: 
![image](https://user-images.githubusercontent.com/70588262/115880063-4f355e00-a418-11eb-9aac-8853ee521671.png)

## Steps to reproduce the problem ##
1. sudo apt-get install cmake libfftw3-dev libmbedtls-dev libboost-program-options-dev libconfig++-dev libsctp-dev 
2. install UHD libraries 
3. Download and build srsLTE from github
4. sudo make install
5. srslte_install_configs.sh user
6. running with default settings, IMSI value is same at ue.conf ( machine 1 ) and user_db.csv ( machine 2 )
7. launching sudo srsepc from  /etc/srslte directory from machine 1 : successful launch 
8. launching sudo srsenb from /etc/srslte directory from machine 1 : successful launch 
9. launching sudo srsue from machine 2: able to launch without any errors.

## Additional Information ##
I was able to succesfully do COTS UE application, using x310 and samusung phone using USIM. ( here had updated correct IMSI at user_db.csv file).

**Comment by andrepuschmann** [comment]
Please increase your socket buffers as highlighted by UHD for the X310.
```
See the transport application notes on buffer resizing.
Please run: sudo sysctl -w net.core.wmem_max=2426666
```
If this is fixed. Adjust the gains levels for both eNB and UE. Note that the X310 uses much lower gain values for Tx/Rx. Send logs files if needed.
