### ISSUE TITLE
srsLTE connect one EPC to multiple eNBs using ZeroMQ

### ISSUE THREAD

**Issue by QingRice** [srsran/srsRAN_4G#690]
## Issue Description ##

Hi there, 

I try to connect two eNBs (each eNB connects to one UE) to one EPC using ZeroMQ, it shows attach successfully and assigns IP addresses to UEs. But when I ping them, they failed (As attached pic). Do you have any suggestions? How many eNBs can an EPC connect to at most? 

What’s more, in the ZeroMQ guide, it says “currently only support single eNB and single UE”. If I want to connect multiple UEs to one eNBs using ZeroMQ, which part of the code needs to be modified? Thanks~

**Comment by sonium-labs** [comment]
Hi, please refer to my reply in #818 regarding a multiple UE/single eNB setup.
