### ISSUE TITLE
Error timed out while receiving smaples from UHD

### ISSUE THREAD

**Issue by klingeni** [srsran/srsRAN_4G#711]
## Issue Description ##
Running "srsue" in ubuntu 18.04.4 terminal or running any other "ue" example leads to following error messages:
Error timed out while receiving samples from UHD
Error receiving samples
Error calling srsran_ue_sync_work

## Setup Details ##
I am using an Ettus B210 SDR and latest uhd drivers with an IntelNUC PC runnung on Ubuntu 18.04.4

## Expected Behavior ##
Continous running of for example "./pdsch_ue -f 1815000000" in terminal while received data is shown in the srsGUI

## Actual Behaviour ##
The example start succesfull, cell id is found and GUI starts as well. But after less than one second the error messages appear again and again, until I stop the program with Ctrl+C.

## Steps to reproduce the problem ##
Simply running "./pdsch_ue" in the examples folder or srsue directly in "home"
The two screenshots are displaying these two examples
![Screenshot from 2021-07-29 20-19-03](https://user-images.githubusercontent.com/83959756/127545321-100ea868-eef8-4578-9ed5-fcfc2451c980.png)
![Screenshot from 2021-07-29 20-18-42](https://user-images.githubusercontent.com/83959756/127545324-a8ba4a46-dc29-4985-bcfc-85f73eee766a.png)

**Comment by ismagom** [comment]
You should run with `sudo` and try again. Re-open if you still see the issue. Thanks
