### ISSUE TITLE
NB-IoT example in srsRAN

### ISSUE THREAD

**Issue by divyansh79** [srsran/srsRAN_4G#713]
**Detail Explanation of Problem**
I am trying to decode MIB and SIB of NB-IoT using srsLTE NB-IoT application note. I am able to get the frequency of the carrier using cell_search_nbiot example but when I am using that frequency in npdsch_ue I am able to get the message MIB decode but neither SIB1 and SIB2 are never decoded and I keep on getting the same message as as shown in the attachment. The npdsch.pcap file that gets written in the tmp folder is also empty with 0 byte of data.

**Setup**
I am using Lime SDR for attaching to NB-IoT network and working on Debian Release 10 operating system

**Expected behavior**
As shown in the example I expect that as soon as the MIB is decoded SIB should be decoded as well. 

**Actual results**
But the actual results are that only MIB is decoded and the SDR keep on searching for PSS and again only MIB is decoded.

![MIB_GIT](https://user-images.githubusercontent.com/66906744/128188095-b214afcc-949e-41be-9713-8c99f60b8bf9.png)
![MIB2](https://user-images.githubusercontent.com/66906744/128188171-4eb55601-7d2e-4139-bbe6-31c4307708af.png)

**Comment by divyansh79** [comment]
If anyone has any experience in this than can you please help.

**Comment by andrepuschmann** [comment]
If the MIB is decoded ok the cell ID, etc match. Perhaps the signal is too weak for the SIB? Try to get closer to the cell.
