### ISSUE TITLE
virtual ue to enb, at srate 1.92 hangs at "Waiting PHY to initialize ..." on Pi4

### ISSUE THREAD

**Issue by anarkiwi** [srsran/srsRAN_4G#721]
## Issue Description ##
It appears the Pi4 has insufficient CPU for zmq-based ue and enbs to come up on the same machine. Even at the lowest possible sample rate, the ue is never able to initialize the phy, staying pegged at 100%. The zmq TCP connections are successfully made, but there is no zmq traffic as the phy layer never initializes.

Perhaps it is not practical to support zmq on Pi?

## Setup Details ##
https://docs.srslte.com/en/latest/app_notes/source/zeromq/source/index.html on Pi4 w/Ubuntu 20.04.3.

## Expected Behavior ##
Tunnel between enb and ue comes up.

## Actual Behaviour ##
ue hangs at 100% CPU at Waiting PHY to initialize ...

## Steps to reproduce the problem ##
https://docs.srslte.com/en/latest/app_notes/source/zeromq/source/index.html on Pi4 w/Ubuntu 20.04.3.

## Additional Information ##
Attempted on 4G and 8G Pis4s, with sufficient power and cooling to ensure no throttling, and the cpufreq governor set to "performance".

**Comment by andrepuschmann** [comment]
We don't usually run ZMQ on the Pi4 but there is no reason why it shouldn't work. I suggest to wait. The PHY init takes a looooong time. I am confident it will finish eventually.

**Comment by anarkiwi** [comment]
Thanks. I waited an hour. :) That should have been enough?

**Comment by frankist** [comment]
zmq doesn't require real-time performance. Even if it is slow, it should work. Did you notice anything unusual in memory usage?

**Comment by anarkiwi** [comment]
Apologies I missed the update. No didn't seem to be any leak or OOM. srsue just spun until I stopped it after an hour. Very happy to try any ideas if you like? I have tried it on two Pi4s, same behavior.
