### ISSUE TITLE
UHD Error : Exception caught in safe-call

### ISSUE THREAD

**Issue by kielcondi** [srsran/srsRAN_4G#732]
## Issue Description ##
UHD Error : Exception caught in safe-call

## Setup Details ##
I am running srsLTE 20.10.1 with UHD 3.15.0. 
I have EPC and ENB and a Front-End.
Images below are the error code I am experiencing.
From our previous testing, it runs with the same set-up but after some time it started to log error codes. The problem got resolved from changing B210 cable port to CPU, but it re-occurs after some time. What will likely be the problem of my set-up? 
Thank you so much.

![image](https://user-images.githubusercontent.com/89245337/136517409-7c19a57f-e8f0-49f1-9f47-59a3c476a330.png)
![image](https://user-images.githubusercontent.com/89245337/136517429-37748936-dcff-4ecb-8a75-43e92aa1b816.png)

**Comment by joxekblad** [comment]
Having the same problem. Ettus closed down their support. National Instruments are doing everything they can to stay away from customer contact.
