### ISSUE TITLE
UE can't establish connection to eNB / zero bitrate. 

### ISSUE THREAD

**Issue by anasalbakri** [srsran/srsRAN_4G#746]
## Issue Description ##
I'm using 2 USRP B210 devices as front-ends with two Linux PCs, one as a UE and another as eNB and EPC. I have installed srsran successfully on both Linux devices with UHD driver and all required libraries. 
However, what I'm getting is either connection not established, or it is established but no packets being transmitted (0 OK and 0 bitrate). 
I have tried initially the default configuration files and also tried to modify them by increasing gain or changing band but still I got the same output.   

## Setup Details ##
2 Linux PCS (one UE and one eNB) 2 USRP B210 (using RF A) of each USRP with 2 antennas on each USRP connected to TX/RX and RX2 
Trying same earfcn on both UE and eNB. Tried default earfcn of 3350 and also other valus but none produced desired output. 

## Expected Behavior ##
Connection should be established. packets should be transmitted and bitrate should be above 0. 

## Actual Behaviour ##
Output from UE: 
sudo srsue
Reading configuration file /root/.config/srsran/ue.conf...

Built in Release mode using commit 89f16eed2 on branch master.

Opening 1 channels in RF device=default with args=default
[INFO] [UHD] linux; GNU C++ version 9.3.0; Boost_107100; UHD_3.15.0.HEAD-0-gaea0e2de
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
Waiting PHY to initialize ... done!
Attaching UE...
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=0.2 KHz
tFound PLMN:  Id=00101, TAC=7
Random Access Transmission: seq=27, tti=3701, ra-rnti=0x2
RRC Connected
Random Access Complete.     c-rnti=0x46, ta=1

Enter t to stop trace.
Warning: Detected Radio-Link Failure
RRC IDLE
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
t--- disconnected ---

Enter t to restart trace.
Attach failed (attempt 1/5)
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=-0.0 KHz
tFound PLMN:  Id=00101, TAC=7

Enter t to stop trace.
Random Access Transmission: seq=24, tti=10101, ra-rnti=0x2
RRC Connected
Random Access Complete.     c-rnti=0x47, ta=1
---------Signal----------|-----------------DL-----------------|-----------UL-----------
 cc  pci  rsrp  pl   cfo | mcs  snr  iter  brate  bler  ta_us | mcs   buff  brate  bler
  0    1   -83  83   -23 |   3   17   0.5    835    0%    0.0 |   1     53     56   57%
Warning: Detected Radio-Link Failure
RRC IDLE
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
Attach failed (attempt 2/5)
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
--- disconnected ---
.
Found Cell:  Mode=FDD, PCI=1, PRB=50, Ports=1, CFO=0.1 KHz
Found PLMN:  Id=00101, TAC=7
Random Access Transmission: seq=24, tti=6901, ra-rnti=0x2
RRC Connected
Random Access Complete.     c-rnti=0x48, ta=1
Warning: Detected Radio-Link Failure
RRC IDLE

![Screenshot from 2021-10-27 09-27-33](https://user-images.githubusercontent.com/35381587/139079268-b980e066-1bac-403e-8f50-2d29ebb51cd9.png)

![Screenshot from 2021-10-25 16-44-41](https://user-images.githubusercontent.com/35381587/139080637-a8ca5a76-7c63-40cd-9369-83876ba4d721.png)

![Screenshot from 2021-10-25 16-40-13](https://user-images.githubusercontent.com/35381587/139081434-bad85c73-9955-4bfa-bd62-37240f5112b3.png)

![Screenshot from 2021-10-25 16-44-39](https://user-images.githubusercontent.com/35381587/139081443-39c9fd3a-4b8c-4b62-b655-735fa3871862.png)

## Steps to reproduce the problem ##
sudo srsepc on one terminal in PC1
sudo srsend on another terminal in PC1
sudo srsue on one PC2 
default configuration files. 

## Additional Information ##
[Any additional information, configuration or data that might be necessary to reproduce the issue]

**Comment by jestrada2006** [comment]
I had a similar issue and it was because my RRC Inativity timer was really short.  It is located near the bottom of enb.conf.  You need to set it higher.  It appears, for me, that the ue will drop a connection, based on this timer, if no traffic is transmitted through the system.
