### ISSUE TITLE
NB-IoT / LTE-M support in srsRAN

### ISSUE THREAD

**Issue by Tim-Conrad** [srsran/srsRAN_4G#747]
Are there any plans to fully support NB-IoT/LTE-M? According to https://github.com/srsran/srsRAN/issues/511 there is no support in the open source nor in the commercial version.

I would like to use srsRAN to debug the application traffic (tcp/udp data) between the UE and the eNB. Would this be possible with the current state?

**Comment by VikrantDigiCat** [comment]
Hi @andrepuschmann 
This appnote is no longer available. Could you please reshare it?
I'm trying to setup an NBIoT network in our lab using an NBIoT eNodeB+srsEPC. However, the NBIoT UEs are unable to get an IP address.

**Comment by Nickisat** [comment]
Try this link in terms of the NB-IoT phy (physical layer) signalling tests : 

https://docs.srsran.com/projects/4g/en/latest/app_notes/source/nbiot/source/index.html NB-IoT Signalling — srsRAN 4G 23.11 documentation

As Andre has commented, srsRAN does not currently support a full NB-IoT implementation. You can test MIB, SIB1 and SIB2 decoding using the UE test application...but this does not support the required uplink functionality in terms of UE attach and establishing IP connectivity with the eNB/EPC

**Comment by Nickisat** [comment]
I'm sure you are...but it won't be NB-IoT as Andre has already commented
