### ISSUE TITLE
unable to see RRC message

### ISSUE THREAD

**Issue by mimo123-code** [srsran/srsRAN_4G#772]
**ISSUE DISCRIPTION**
Unable to see RRC message in wireshark where UE and enodeb are  gnu radio ZeroMQ 

## Setup Details ##
System Hardware: Intel NUC
Operating System: Ubuntu 20.04.3 LTS (Linux kernel version 5.11.0-40-generic)
RF front-end: USRP X310 with UBX-160 daughterboards
Library & Driver versions: GNU C++ version 9.3.0; Boost_107100; UHD_3.15.0.0-release
Connectivity: 10Gbps ethernet connection using an SFP+ connector and a Cat. 6 RJ45 cable.

## Expected Behavior ##
When given RRC filter in wireshark RRC packets should Come

## Actual Behaviour ##
able to see only S1AP/NAS messages

**Comment by ismagom** [comment]
Please provide logs and report again.
