### ISSUE TITLE
Ping between UEs

### ISSUE THREAD

**Issue by ahnaseri** [srsran/srsRAN_4G#781]
Hi everyone

I run a setup with 4 identical Samsung UE.
The user database file is as follow and i set static IP assignment.

ue1,mil,,,opc,,8000,000000002eb4,7,172.16.0.2
ue2,mil,,opc,,8000,000000002cc7,7,172.16.0.3
ue3,mil,,opc,,8000,000000001a78,7,172.16.0.4
ue4,mil,,opc,,8000,000000001a78,7,172.16.0.5

everything is OK and UEs have access to Internet. BUT UE4 can not ping UE3 and therefor VOIP call or VideoCall between these two UEs is unidirectional. For other UEs there is no such problem.

What the problem can be?!!

**Comment by ismagom** [comment]
Provide logs so others can help you. Thanks
