### ISSUE TITLE
SRSUE TDD Problem

### ISSUE THREAD

**Issue by jtang613** [srsran/srsRAN_4G#803]
## Issue Description ##
I'm having trouble getting SRSUE to connect to TDD on a Band 40 COTS femto. FDD Band 1 on a similarly-configured device from the same vendor does work.

Log is reporting 
```RA response not received within the response window```
This is followed by T300 timeouts leading to SRSUE abandoning the attach attempt.

## Setup Details ##
SRSUE (LimeSDR) -> TDD2300 femto -> Open5gs  (breaks on attach after T300 timeout)
SRSUE (LimeSDR) -> FDD2100 femto -> Open5gs  (stable connection)

## Expected Behavior ##
TDD should connect. I last saw this working on a 19.x release, but those branches no longer compile in my environment.

I'm not sure if what I'm observing is a symptom or the cause - but I'm willing to try any recommendations or patches.

## Additional Information ##
See attached ue.log
[ue.log](https://github.com/srsran/srsRAN/files/8020023/ue.log)

**Comment by andrepuschmann** [comment]
I am afraid the TDD support in the UE hasn't been the focus for a while. There is an suggestion https://github.com/srsran/srsRAN/issues/770 that might help.
