### ISSUE TITLE
COTS UE cannot find LTE network

### ISSUE THREAD

**Issue by SpongeBobaa** [srsran/srsRAN_4G#908]
## Issue Description ##
[Describe the issue in detail]
When I run `sudo srsepc` and `sudo srsenb`, the corresponding network cannot be found using COTS UE. I changed the `MNC` and `MCC` in epc.conf and enb.conf to 460 and 40. I also changed the value of `DL_EARFN`. None of these methods work.

## Setup Details ##
[Specify details of the test setup. This would help us reproduce the problem reliably]
Ubuntu20.04
USRP B210
Linux version 5.13.0-51-generic (buildd@lcy02-amd64-046) (gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #58~20.04.1-Ubuntu SMP Tue Jun 14 11:29:12 UTC 2022
Followed the docs guide for COTS UE step-by-step

## Expected Behavior ##
COTS UE could find LTE network and connect it.

## Actual Behaviour ##
COTS UE could not find the LTE network.

Here is display of EPC 

```
Built in Release mode using commit f2dff0b7a on branch master.


---  Software Radio Systems EPC  ---

Couldn't open , trying /root/.config/srsran/epc.conf
Reading configuration file /root/.config/srsran/epc.conf...
Couldn't open user_db.csv, trying /root/.config/srsran/user_db.csv
HSS Initialized.
MME S11 Initialized
MME GTP-C Initialized
MME Initialized. MCC: 0xf460, MNC: 0xff40
SPGW GTP-U Initialized.
SPGW S11 Initialized.
SP-GW Initialized.
Received S1 Setup Request.
S1 Setup Request - eNB Name: srsenb01, eNB id: 0x19b
S1 Setup Request - MCC:460, MNC:40
S1 Setup Request - TAC 7, B-PLMN 0x64f004
S1 Setup Request - Paging DRX v128
Sending S1 Setup Response
```

Here is display of eNodeB 

```
Active RF plugins: libsrsran_rf_uhd.so
Inactive RF plugins: 
---  Software Radio Systems LTE eNodeB  ---

Couldn't open , trying /root/.config/srsran/enb.conf
Reading configuration file /root/.config/srsran/enb.conf...
Couldn't open sib.conf, trying /root/.config/srsran/sib.conf
Couldn't open rr.conf, trying /root/.config/srsran/rr.conf
Couldn't open rb.conf, trying /root/.config/srsran/rb.conf
WARNING: Could not verify cpu0 scaling governor
WARNING: Could not verify cpu1 scaling governor
WARNING: Could not verify cpu2 scaling governor
WARNING: Could not verify cpu3 scaling governor

Built in Release mode using commit f2dff0b7a on branch master.

Opening 1 channels in RF device=default with args=default
Supported RF device list: UHD file
Trying to open RF device 'UHD'
[INFO] [UHD] linux; GNU C++ version 9.4.0; Boost_107100; UHD_4.2.0.0-0ubuntu1~focal1
[INFO] [LOGGING] Fastpath logging disabled at runtime.
Opening USRP channels=1, args: type=b200,master_clock_rate=23.04e6
[INFO] [UHD RF] RF UHD Generic instance constructed
[INFO] [B200] Detected Device: B210
[INFO] [B200] Operating over USB 3.
[INFO] [B200] Initialize CODEC control...
[INFO] [B200] Initialize Radio control...
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Performing register loopback test... 
[INFO] [B200] Register loopback test passed
[INFO] [B200] Asking for clock rate 23.040000 MHz... 
[INFO] [B200] Actually got clock rate 23.040000 MHz.
RF device 'UHD' successfully opened

==== eNodeB started ===
Type <t> to view trace
Setting frequency: DL=1935.0 Mhz, UL=1855.0 MHz for cc_idx=0 nof_prb=50
[INFO] [UHD RF] Tx while waiting for EOB, timed out... 2.54903 >= 0. Starting new burst...
[INFO] [UHD RF] Tx while waiting for EOB, timed out... 2.59863 >= 0. Starting new burst...
t
Enter t to stop trace.
RF status: O=9, U=17, L=899
RF status: O=10, U=26, L=949
RF status: O=10, U=20, L=951
t
Enter t to restart trace.
```

At the same time, I checked the network status as follows
```
srs_spgw_sgi: flags=4305<UP,POINTOPOINT,RUNNING,NOARP,MULTICAST>  mtu 1500
        inet 172.16.0.1  netmask 255.255.255.0  destination 172.16.0.1
        inet6 fe80::da5e:4c33:65cd:681  prefixlen 64  scopeid 0x20<link>
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 500  (not specified)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 9  bytes 432 (432.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

## Steps to reproduce the problem ##
Install uhd
Install gnuradio
Install srsran
Followed the docs guide for COTS UE step-by-step.

## Additional Information ##
 I changed the `MNC` and `MCC` in **epc.conf** and **enb.conf** to **460** and **40**. And I changed the `dl_earfcn` in **rr.conf** from **3350** to **250** .

**Comment by andrepuschmann** [comment]
Hey,

```
RF status: O=9, U=17, L=899
RF status: O=10, U=26, L=949
RF status: O=10, U=20, L=951
```
is this always happening? I.e. is the LED on the USRP blinking? If so you have lates and the UE will not be able to sync on the cell.

**Comment by SpongeBobaa** [comment]
Thank you for your help！
Yes, it is always happening. And the LED on the USRP is always blinking! I will try to install the Linux low latency kernel. Hope that helps to solve the problem.
I would like to ask if the LED is always on instead of blinking, does that mean there is no delay?

**Comment by SpongeBobaa** [comment]
> Hey,
> 
> ```
> RF status: O=9, U=17, L=899
> RF status: O=10, U=26, L=949
> RF status: O=10, U=20, L=951
> ```
> 
> is this always happening? I.e. is the LED on the USRP blinking? If so you have lates and the UE will not be able to sync on the cell.

Thank you for your help！
Yes, it is always happening. And the LED on the USRP is always blinking! I will try to install the Linux low latency kernel. Hope that helps to solve the problem.
I would like to ask if the LED is always on instead of blinking, does that mean there is no delay?

**Comment by SpongeBobaa** [comment]
well, I think I solved the existing delay problem. Now the LED on the USRP is always on . 

Unfortunately I still can't find the LTE network.

**Comment by bedrankara** [comment]
Which COTS UE are you currently using? Depending on the manufacturer there might be additional steps to take.

**Comment by SpongeBobaa** [comment]
Thank you all for your help！
After solving the delay problem, I finally succeeded in trying different frequency point numbers and frequencies!
I use OPPO ACE to find the network signal when `DL_EARFCN=1300` or `=1500`.

**Comment by brendan-mcauliffe** [comment]
Closing issue.

**Comment by c-aman** [comment]
Hi @SpongeBobaa ,
I was setting up the same setup with Ubuntu18 & USRP B210 and I am facing the same issue, can you describe which values you have changed and from which config files.
